version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "uddhav"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      development:
        patterns:
          - "@types/*"
          - "vitest*"
          - "eslint*"
          - "prettier*"
        update-types:
          - "minor"
          - "patch"
      production:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "vitest*"
          - "eslint*"
          - "prettier*"
        update-types:
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "uddhav"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"