version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 10
    target-branch: 'develop'
    reviewers:
      - 'uddhav'
    labels:
      - 'dependencies'
      - 'npm'
    groups:
      production:
        patterns:
          - '@modelcontextprotocol/*'
          - 'chalk'
          - 'compromise'
          - 'yargs'
          - 'zod'
        update-types:
          - 'minor'
          - 'patch'
      development:
        patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - '@vitest/*'
          - 'vitest'
          - 'typescript'
          - 'eslint*'
          - 'prettier*'
        update-types:
          - 'minor'
          - 'patch'
      commitlint:
        patterns:
          - '@commitlint/*'
          - 'commitizen'
          - 'cz-*'
          - 'husky'
          - 'lint-staged'
          - 'standard-version'
        update-types:
          - 'minor'
          - 'patch'
      semantic-release:
        patterns:
          - '@semantic-release/*'
          - 'semantic-release'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: '@modelcontextprotocol/sdk'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Maintain GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    target-branch: 'develop'
    reviewers:
      - 'uddhav'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'
