name: Update Badges

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-badges:
    name: Update README Badges
    runs-on: ubuntu-latest
    if: github.event.workflow_run.head_branch == 'main'
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📊 Update badges in README
        run: |
          # Check if badges section exists
          if ! grep -q "## Badges" README.md; then
            # Add badges section after the title
            sed -i '3i\\n## Badges\n\n[![CI Pipeline](https://github.com/uddhav/creative-thinking/actions/workflows/ci.yml/badge.svg)](https://github.com/uddhav/creative-thinking/actions/workflows/ci.yml)\n[![codecov](https://codecov.io/gh/uddhav/creative-thinking/branch/main/graph/badge.svg)](https://codecov.io/gh/uddhav/creative-thinking)\n[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)\n[![npm version](https://badge.fury.io/js/creative-thinking.svg)](https://badge.fury.io/js/creative-thinking)\n' README.md
            
            # Commit changes
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add README.md
            git diff --staged --quiet || git commit -m "docs: Add status badges [skip ci]"
            git push
          fi